version: "3.8"

services:
  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    environment:
      - MYSQL_HOST=db_slim_export
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=slim_export

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - APP_NAME='hcpro-exports-slim'
      - APP_USER='hugo'
      - APP_PASS='1234'
    depends_on:
      - php

  db:
    container_name: slim_mysql
    image: mysql:8.0
    ports:
      - '3307:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=slim_export

  phpmyadmin:
    container_name: slim_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret

  rabbitmq:
    image: rabbitmq:management
    container_name: slim_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
